aliases:
  "ютуб": "https://youtube.com"
  "youtube": "https://youtube.com"
  "google": "https://www.google.com"
  "гугл": "https://www.google.com"
  "chatgpt": "https://chatgpt.com"
  "вконтакте": "https://vk.com"
  "вк": "https://vk.com"
  "телеграм": "https://web.telegram.org"
  "telegram": "https://web.telegram.org"
  "discord": "https://discord.com/app"
  "steam": "https://store.steampowered.com"
  "spotify": "https://open.spotify.com"
  "github": "https://github.com"
  "yandex": "https://yandex.ru"
